force-app/main/default/objects/Material__c/Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material__c/fields/Blocked_Stock_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Stock_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Blocked Stock Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Order_Material__c/Work_Order_Material__c.object-meta.xml
<CustomObject>
    <label>Work Order Material</label>
    <nameField>
        <label>Work Order Materials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Material__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Material__c</referenceTo>
    <relationshipLabel>Work Order Materials</relationshipLabel>
    <relationshipName>Work_Order_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Material__c/fields/Required_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Required_Quantity__c</fullName>
    <label>Required Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WorkOrderMaterialService.cls
public with sharing class WorkOrderMaterialService {
    public static void handleafterInsert(List<Work_Order_Material__c> newWorkOrderMaterials) {
        if(!newWorkOrderMaterials.isEmpty()){
            Set<Id> materialIds = new Set<Id>();
            for(Work_Order_Material__c newWorkOrderMaterial : newWorkOrderMaterials){
                if(newWorkOrderMaterial.Material__c != null){
                    materialIds.add(newWorkOrderMaterial.Material__c);
                }
            }

            if(!materialIds.isEmpty()){
                Map<Id, Material__c> materials = MaterialDataService.getMaterialsById(materialIds);
                List<Material__c> materialList = new List<Material__c>();

                for(Work_Order_Material__c newWorkOrderMaterial : newWorkOrderMaterials){
                    Decimal blockedQuantity = materials.get(newWorkOrderMaterial.Material__c).Blocked_Stock_Quantity__c ?? 0.00;
                    materialList.add(
                        new Material__c(
                            Id = newWorkOrderMaterial.Material__c,
                            Blocked_Stock_Quantity__c = blockedQuantity + newWorkOrderMaterial.Required_Quantity__c
                        )
                    );
                }
                MaterialDataService.updateMaterials(materialList);
            }
        }
    }
}