force-app/main/default/objects/Material__c/Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Requirements_Planning__c/Material_Requirements_Planning__c.object-meta.xml
<CustomObject>
    <label>Material Requirements Planning</label>
    <nameField>
        <displayFormat>MRP-{000000}</displayFormat>
        <label>Material Requirements Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Requirements Plannings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Requirements_Planning__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Material</label>
    <referenceTo>Material__c</referenceTo>
    <relationshipLabel>Material Requirements Plannings</relationshipLabel>
    <relationshipName>Material_Requirements_Plannings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material_Requirements_Planning__c/fields/Quantity_to_Buy__c.field-meta.xml
<CustomField>
    <fullName>Quantity_to_Buy__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Quantity to Buy</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Material_Requirements_Planning__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>PO Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MRPDataService.cls
public with sharing class MRPDataService {
    public static List<Material_Requirements_Planning__c> getAllOpenMRP (){
        return new List<Material_Requirements_Planning__c>([
            SELECT Id, Name, Quantity_to_Buy__c, Material__c, Status__c
            FROM Material_Requirements_Planning__c 
            WHERE Status__c = 'Open'
            WITH SYSTEM_MODE
        ]);
   }

   public static void upsertMRP(List<Material_Requirements_Planning__c> mrpToUpsert) {
        if (!mrpToUpsert.isEmpty()) {
            upsert as system mrpToUpsert;
        }
    }
}