force-app/main/default/objects/Material__c/Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material__c/fields/Blocked_Stock_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Stock_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Blocked Stock Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Material_Requirements_Planning__c/Material_Requirements_Planning__c.object-meta.xml
<CustomObject>
    <label>Material Requirements Planning</label>
    <nameField>
        <displayFormat>MRP-{000000}</displayFormat>
        <label>Material Requirements Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Requirements Plannings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Requirements_Planning__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Material</label>
    <referenceTo>Material__c</referenceTo>
    <relationshipLabel>Material Requirements Plannings</relationshipLabel>
    <relationshipName>Material_Requirements_Plannings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material_Requirements_Planning__c/fields/Quantity_to_Buy__c.field-meta.xml
<CustomField>
    <fullName>Quantity_to_Buy__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Quantity to Buy</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Material_Requirements_Planning__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>PO Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MRPGenerator.cls
public with sharing class MRPGenerator {
    public static void generateMRP(){
        List<Material_Requirements_Planning__c> existingMRP = MRPDataService.getAllOpenMRP();
        List<Material__c> allMaterials = MaterialDataService.getAllMaterials();
        List<Material_Requirements_Planning__c> newMRPs = new List<Material_Requirements_Planning__c>();
        List<Material_Requirements_Planning__c> updateMRPs = new List<Material_Requirements_Planning__c>();
        Map<Id, Decimal> materialToQuanitityToBuyMap = new Map<Id, Decimal>();
        Map<Id, Id> materialToMRPMap = new Map<Id, Id>();
        Set<Id> existingMRPMaterials = new Set<Id>();

        if (!existingMRP.isEmpty()){
            for (Material_Requirements_Planning__c mrp: existingMRP){
                if (mrp.Material__c != null) {
                    materialToQuanitityToBuyMap.put(mrp.Material__c, mrp.Quantity_to_Buy__c ?? 0);
                    materialToMRPMap.put(mrp.Material__c, mrp.Id);
                    existingMRPMaterials.add(mrp.Material__c);
                }
            }
        }

        if (!allMaterials.isEmpty()){
            for (Material__c material : allMaterials) {

                if (material.Blocked_Stock_Quantity__c == null || material.Stock_Quantity__c == null) {
                    continue; 
                }
                
                Decimal quantityToBuy = material.Blocked_Stock_Quantity__c - material.Stock_Quantity__c;
                
                if (!existingMRPMaterials.contains(material.Id) && material.Blocked_Stock_Quantity__c > material.Stock_Quantity__c) {
                    newMRPs.add(
                        new Material_Requirements_Planning__c(
                            Material__c = material.Id,
                            Quantity_to_Buy__c = quantityToBuy,
                            Status__c = 'Open'
                        )
                    );
                } else if (existingMRPMaterials.contains(material.Id) && material.Blocked_Stock_Quantity__c > material.Stock_Quantity__c) {
                    Decimal existingQuantity = materialToQuanitityToBuyMap.get(material.Id) ?? 0;
                    
                    if (existingQuantity != quantityToBuy) {
                        updateMRPs.add(
                            new Material_Requirements_Planning__c(
                                Id = materialToMRPMap.get(material.Id),
                                Quantity_to_Buy__c = quantityToBuy
                            )
                        );
                    }
                }
            }

            if(!newMRPs.isEmpty()){
                MRPDataService.upsertMRP(newMRPs);
                System.debug('Created ' + newMRPs.size() + ' new MRPs');
            }

            if(!updateMRPs.isEmpty()){
                MRPDataService.upsertMRP(updateMRPs);
                System.debug('Updated ' + updateMRPs.size() + ' MRPs');
            }
            
            if(newMRPs.isEmpty() && updateMRPs.isEmpty()){
                System.debug('No MRP records to create or update');
            }
        }
    }
}