force-app/main/default/objects/Material__c/Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Adjustment__c/Stock_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Stock Adjustment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Stock Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Adjustment__c/fields/Adjustment_Date__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Date__c</fullName>
    <label>Adjustment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stock_Adjustment__c/fields/Adjustment_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Quantity__c</fullName>
    <label>Adjustment Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Adjustment__c/fields/IsCreatedFromMaterial__c.field-meta.xml
<CustomField>
    <fullName>IsCreatedFromMaterial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCreatedFromMaterial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stock_Adjustment__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Material__c</referenceTo>
    <relationshipLabel>Stock Adjustments</relationshipLabel>
    <relationshipName>Stock_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Adjustment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Stock_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StockAdjustmentService.cls
public with sharing class StockAdjustmentService {
    
    public static void handleBeforeInsert(List<Stock_Adjustment__c> stockAdjustments) {
        
        if(stockAdjustments != null && !stockAdjustments.isEmpty()){
            Set<Id> materialIds = new Set<Id>();
            
            for (Stock_Adjustment__c adj : stockAdjustments) {
                if (adj.Material__c != null && adj.Adjustment_Quantity__c != null) {
                    materialIds.add(adj.Material__c);
                }
            }
            
            if (materialIds.isEmpty()) {
                return;
            }
            
            Map<Id, Material__c> materialsMap = MaterialDataService.getMaterialsById(materialIds);
            
            for (Stock_Adjustment__c adj : stockAdjustments) {
                Material__c material = materialsMap.get(adj.Material__c);
                if (material != null) {
                    Decimal currentStock = material.Stock_Quantity__c != null ? material.Stock_Quantity__c : 0;
                    Decimal newStock = currentStock + adj.Adjustment_Quantity__c;
                    
                    if (newStock < 0) {
                        adj.addError(MessageUtility.ERROR_NEGATIVE_STOCK_QUANTITY);
                        
                    }
                }
            }
        }
    }
    
    public static void handleAfterInsert(List<Stock_Adjustment__c> newStockAdjustmentRecords) {
        
        if(newStockAdjustmentRecords != null && !newStockAdjustmentRecords.isEmpty()){
            List<Stock_Adjustment__c> adjustmentsToUpdate = new List<Stock_Adjustment__c>();
            List<Stock_Adjustment__c> adjustmentsForMaterialUpdate = new List<Stock_Adjustment__c>();
            
            for (Stock_Adjustment__c adj : newStockAdjustmentRecords) {
                Stock_Adjustment__c updateAdj = new Stock_Adjustment__c();
                updateAdj.Id = adj.Id;
                updateAdj.Adjustment_Date__c = System.now();
                updateAdj.User__c = UserInfo.getUserId();
                adjustmentsToUpdate.add(updateAdj);
                
                if (adj.IsCreatedFromMaterial__c != true) {
                    adjustmentsForMaterialUpdate.add(adj);
                }
            }
            
            if (!adjustmentsToUpdate.isEmpty()) {
                StockAdjustmentDataService.updateStockAdjustments(adjustmentsToUpdate);
            }
            
            if (!adjustmentsForMaterialUpdate.isEmpty()) {
                updateMaterialQuantity(adjustmentsForMaterialUpdate);
            }
        }
    }
    
    
    private static void updateMaterialQuantity(List<Stock_Adjustment__c> stockAdjustments) {
        if(stockAdjustments != null && !stockAdjustments.isEmpty()){
            Map<Id, Decimal> materialAdjustments = new Map<Id, Decimal>();
            
            for (Stock_Adjustment__c adj : stockAdjustments) {
                if (adj.Material__c != null && adj.Adjustment_Quantity__c != null) {
                    Decimal currentStockQnty = materialAdjustments.get(adj.Material__c);
                    Decimal totalQuantity = (currentStockQnty != null ? currentStockQnty : 0) + adj.Adjustment_Quantity__c;
                    materialAdjustments.put(adj.Material__c, totalQuantity);
                }
            }
            
            if (!materialAdjustments.isEmpty()) {
                Map<Id, Material__c> materials = MaterialDataService.getMaterialsById(materialAdjustments.keySet());
                MaterialService.isUpdateFromAdjustment = true;
                
                for (Material__c material : materials.values()) {
                    material.Stock_Quantity__c = (material.Stock_Quantity__c != null ? material.Stock_Quantity__c : 0) + materialAdjustments.get(material.Id);
                }
                
                MaterialDataService.updateMaterials(materials.values());
                MaterialService.isUpdateFromAdjustment = false;
            }
        }
    }
}