force-app/main/default/objects/Material__c/Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Material__c/Product_Material__c.object-meta.xml
<CustomObject>
    <label>Product Material</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Product Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Material__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Material__c</referenceTo>
    <relationshipLabel>Product Materials</relationshipLabel>
    <relationshipName>Product_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Material__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Materials</relationshipLabel>
    <relationshipName>Product_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Producttttt__c.field-meta.xml
<CustomField>
    <fullName>Producttttt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Productt</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Material__c/Work_Order_Material__c.object-meta.xml
<CustomObject>
    <label>Work Order Material</label>
    <nameField>
        <label>Work Order Materials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Material__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Material__c</referenceTo>
    <relationshipLabel>Work Order Materials</relationshipLabel>
    <relationshipName>Work_Order_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Material__c/fields/Required_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Required_Quantity__c</fullName>
    <label>Required Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Order_Material__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Order Materials</relationshipLabel>
    <relationshipName>Work_Order_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WorkOrderService.cls
public with sharing class WorkOrderService {
    
    public static void handleBeforeInsert(List<Work_Order__c> newWorkOrders) {
        if(!newWorkOrders.isEmpty()) {
            for(Work_Order__c newWorkOrder : newWorkOrders){
                newWorkOrder.Status__c = 'Not Started';
            }
        }
    }

    public static void handleAfterInsert(List<Work_Order__c> newWorkOrders) {
        System.debug('After Insert');
        System.debug('newWorkOrders: ' + newWorkOrders);
        if(!newWorkOrders.isEmpty()) {
            for(Work_Order__c newWorkOrder : newWorkOrders){
                createWorkOrderMaterials(newWorkOrder);
            }
        }
    }

    public static void createWorkOrderMaterials(Work_Order__c workOrder) {
        List<Product_Material__c> productMaterials  = [SELECT Id, Name, Product__c, Material__c, Quantity__c FROM Product_Material__c WHERE Product__c = :workOrder.Producttttt__c];
        List<Work_Order_Material__c> workOrderMaterials = new List<Work_Order_Material__c>();
        for(Product_Material__c productMaterial : productMaterials) {
            workOrderMaterials.add(
                new Work_Order_Material__c(
                    Work_Order__c = workOrder.Id,
                    Material__c = productMaterial.Material__c,
                    Required_Quantity__c = productMaterial.Quantity__c * workOrder.Quantity__c,
                    Name = productMaterial.Name + ' ' + workOrder.Name
                )
            );
        }

        if(!workOrderMaterials.isEmpty()) {
            System.debug('Work Order materials to insert: ' + workOrderMaterials);
            insert workOrderMaterials;
            System.debug('Work Order materials inserted successfully');
        }
    }
}