force-app/main/default/objects/Material__c/Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material__c/fields/Blocked_Stock_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Stock_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Blocked Stock Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Material__c/Product_Material__c.object-meta.xml
<CustomObject>
    <label>Product Material</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Product Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Material__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Material__c</referenceTo>
    <relationshipLabel>Product Materials</relationshipLabel>
    <relationshipName>Product_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Material__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Materials</relationshipLabel>
    <relationshipName>Product_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Producttttt__c.field-meta.xml
<CustomField>
    <fullName>Producttttt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Productt</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Material__c/Work_Order_Material__c.object-meta.xml
<CustomObject>
    <label>Work Order Material</label>
    <nameField>
        <label>Work Order Materials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Material__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Material__c</referenceTo>
    <relationshipLabel>Work Order Materials</relationshipLabel>
    <relationshipName>Work_Order_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Material__c/fields/Required_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Required_Quantity__c</fullName>
    <label>Required Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Order_Material__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Order Materials</relationshipLabel>
    <relationshipName>Work_Order_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WorkOrderMaterialDataServiceTest.cls
@isTest
public with sharing class WorkOrderMaterialDataServiceTest {
    @TestSetup
    static void setupTestData() {
        
        List<Material__c> materials = new List<Material__c>();
        materials.add(new Material__c(
            Name = 'Test Material 1',
            Blocked_Stock_Quantity__c = 10.00
        ));
        materials.add(new Material__c(
            Name = 'Test Material 2',
            Blocked_Stock_Quantity__c = 5.00
        ));
        insert materials;
        Product__c testProduct = new Product__c(
            Name = 'Test Product 1'
        );
        insert testProduct;

        Product_Material__c productMaterial = new Product_Material__c(
            Product__c = testProduct.Id,
            Material__c = materials[0].Id,
            Quantity__c = 3
        );
        insert productMaterial;

        Work_Order__c testWorkOrder = new Work_Order__c(
            Producttttt__c = testProduct.Id,
            Quantity__c = 1
        );
        insert testWorkOrder;
    }

    @isTest
    static void testWorkOrderMaterialDataServiceInsert() {
        
        List<Material__c> materials = [SELECT Id FROM Material__c LIMIT 1];
        List<Work_Order__c> workOrders = [SELECT Id FROM Work_Order__c];
        
        
        List<Work_Order_Material__c> workOrderMaterials = new List<Work_Order_Material__c>();
        workOrderMaterials.add(new Work_Order_Material__c(
            Material__c = materials[0].Id,
            Required_Quantity__c = 3.00,
            Work_Order__c = workOrders[0].Id
        ));
        
        Test.startTest();
        WorkOrderMaterialDataService.insertWorkOrderMaterials(workOrderMaterials);
        Test.stopTest();
        
        
        List<Work_Order_Material__c> insertedRecords = [SELECT Id, Material__c, Required_Quantity__c FROM Work_Order_Material__c];
        System.assertEquals(2, insertedRecords.size(), 'Two Work Order Material should be inserted');
        System.assertEquals(materials[0].Id, insertedRecords[0].Material__c, 'Material should match');
        System.assertEquals(3.00, insertedRecords[0].Required_Quantity__c, 'Required quantity should match');
    }
}