force-app/main/default/objects/External_Data_Load__c/External_Data_Load__c.object-meta.xml
<CustomObject>
    <label>External Data Load</label>
    <nameField>
        <displayFormat>EDL-{0000}</displayFormat>
        <label>External Data Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Data Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Data_Load__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>External Data Loads</relationshipLabel>
    <relationshipName>External_Data_Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_Data_Load__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Product__c/Order_Product__c.object-meta.xml
<CustomObject>
    <label>Order Product</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Order Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExternalDataQueueableTest.cls
@isTest
public class ExternalDataQueueableTest {

    @testSetup
    static void setupTestData() {
        Product__c prod = new Product__c(Name='Test Product');
        insert prod;

        Account acc = new Account(Name='Test Account');
        insert acc;

        Order ord = new Order(Name='Test Order', AccountId=acc.Id, EffectiveDate=Date.today(), Status='Draft');
        insert ord;

        External_Data_Load__c loadRecord = new External_Data_Load__c(Payload__c='{"order": {}, "orderProducts": []}', Status__c='Pending');
        insert loadRecord;
    }

    @isTest
    static void testSuccess() {
        Product__c prod = [SELECT Id FROM Product__c LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Order ord = [SELECT Id FROM Order LIMIT 1];
        External_Data_Load__c loadRecord = [SELECT Id, Payload__c, Status__c, Error_Message__c FROM External_Data_Load__c LIMIT 1];

        ExternalDataQueueable queueable = new ExternalDataQueueable(loadRecord);

        queueable.custAccount = acc;
        queueable.order = ord;

        queueable.orderProducts =  new List<Order_Product__c>{
            new Order_Product__c(Product__c = prod.Id, Price__c = 1.0, Quantity__c = 5, Order__c = ord.Id)
        };

        Test.startTest();
        System.enqueueJob(queueable);
        Test.stopTest();

        loadRecord = [SELECT Status__c, Error_Message__c FROM External_Data_Load__c WHERE Id = :loadRecord.Id];
        System.assertEquals('Success', loadRecord.Status__c);
        System.assertEquals(null, loadRecord.Error_Message__c);
    }

    @isTest
    static void testPartialSuccess() {
        Product__c prod = [SELECT Id FROM Product__c LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Order ord = [SELECT Id FROM Order LIMIT 1];
        External_Data_Load__c loadRecord = [SELECT Id, Payload__c, Status__c, Error_Message__c FROM External_Data_Load__c LIMIT 1];

        ExternalDataQueueable queueable = new ExternalDataQueueable(loadRecord);

        queueable.custAccount = acc;
        queueable.order = ord;
        
        queueable.orderProducts = new List<Order_Product__c> {
            new Order_Product__c(Product__c = prod.Id, Price__c = 1.0, Quantity__c = 5, Order__c = ord.Id),
            new Order_Product__c(Product__c = null, Price__c = 1.0, Quantity__c = 5, Order__c = '800000000000000AAA')
        };

        Test.startTest();
        System.enqueueJob(queueable);
        Test.stopTest();

        loadRecord = [SELECT Status__c, Error_Message__c FROM External_Data_Load__c WHERE Id = :loadRecord.Id];
        System.debug('Error Message: ' + loadRecord.Error_Message__c);
        System.assertEquals('Partial Success', loadRecord.Status__c);
    }

    @isTest
    static void testAccountFail() {
        Product__c prod = [SELECT Id FROM Product__c LIMIT 1];
        External_Data_Load__c loadRecord = [SELECT Id, Payload__c, Status__c, Error_Message__c FROM External_Data_Load__c LIMIT 1];

        ExternalDataQueueable queueable = new ExternalDataQueueable(loadRecord);

        Test.startTest();
        System.enqueueJob(queueable);
        Test.stopTest();

        loadRecord = [SELECT Status__c, Error_Message__c FROM External_Data_Load__c WHERE Id = :loadRecord.Id];
        System.assertEquals('Failed', loadRecord.Status__c);
    }

    @isTest
    static void testOrderFail() {
        Product__c prod = [SELECT Id FROM Product__c LIMIT 1];
        External_Data_Load__c loadRecord = [SELECT Id, Payload__c, Status__c, Error_Message__c FROM External_Data_Load__c LIMIT 1];
        
        ExternalDataQueueable queueable = new ExternalDataQueueable(loadRecord);
        
        Account acc = new Account(Name='Test Account');
        queueable.custAccount = acc;

        Test.startTest();
        System.enqueueJob(queueable);
        Test.stopTest();

        loadRecord = [SELECT Status__c, Error_Message__c FROM External_Data_Load__c WHERE Id = :loadRecord.Id];
        System.assertEquals('Failed', loadRecord.Status__c);
    }

    @isTest
    static void testOrderItemsFail() {
        Product__c prod = [SELECT Id FROM Product__c LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Order ord = [SELECT Id FROM Order LIMIT 1];
        External_Data_Load__c loadRecord = [SELECT Id, Payload__c, Status__c, Error_Message__c FROM External_Data_Load__c LIMIT 1];

        ExternalDataQueueable queueable = new ExternalDataQueueable(loadRecord);

        queueable.custAccount = acc;
        queueable.order = ord;
        queueable.orderProducts =  new List<Order_Product__c>{};

        Test.startTest();   
        System.enqueueJob(queueable);
        Test.stopTest();

        loadRecord = [SELECT Status__c, Error_Message__c FROM External_Data_Load__c WHERE Id = :loadRecord.Id];
        System.assertEquals('Partial Success', loadRecord.Status__c);
        System.debug('Error Message: ' + loadRecord.Error_Message__c);
    }

    @isTest
    static void testInvalidJson() {
        External_Data_Load__c loadRecord = [SELECT Id, Payload__c, Status__c, Error_Message__c FROM External_Data_Load__c LIMIT 1];
        loadRecord.Payload__c = 'Invalid JSON format';
        
        Test.startTest();
        System.enqueueJob(new ExternalDataQueueable(loadRecord));
        Test.stopTest();

        loadRecord = [SELECT Status__c FROM External_Data_Load__c WHERE Id = :loadRecord.Id];
        System.assertEquals('Failed', loadRecord.Status__c);
    }

    @isTest
    static void testMissingOrder() {
        String payload = '{"orderProducts": []}';
        External_Data_Load__c loadRecord = new External_Data_Load__c(Payload__c=payload);
        insert loadRecord;

        Test.startTest();
        System.enqueueJob(new ExternalDataQueueable(loadRecord));
        Test.stopTest();

        loadRecord = [SELECT Status__c FROM External_Data_Load__c WHERE Id = :loadRecord.Id];
        System.assertEquals('Failed', loadRecord.Status__c);
    }

    @isTest
    static void testExecuteCatchBlock() {
        External_Data_Load__c loadRecord = new External_Data_Load__c(Payload__c='throw', Status__c='Pending');
        insert loadRecord;

        Test.startTest();
        System.enqueueJob(new ExternalDataQueueable(loadRecord));
        Test.stopTest();

        loadRecord = [SELECT Status__c, Error_Message__c FROM External_Data_Load__c WHERE Id = :loadRecord.Id];
        System.assertEquals('Failed', loadRecord.Status__c);
        System.assert(loadRecord.Error_Message__c.contains('DML problem.'));
    }
}