force-app/main/default/objects/External_Data_Load__c/External_Data_Load__c.object-meta.xml
<CustomObject>
    <label>External Data Load</label>
    <nameField>
        <displayFormat>EDL-{0000}</displayFormat>
        <label>External Data Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Data Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Data_Load__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>External Data Loads</relationshipLabel>
    <relationshipName>External_Data_Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_Data_Load__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Product__c/Order_Product__c.object-meta.xml
<CustomObject>
    <label>Order Product</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Order Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExternalDataQueueable.cls
public class ExternalDataQueueable implements Queueable {
    private External_Data_Load__c loadRecord;

    @TestVisible
    private Account custAccount;
    
    @TestVisible
    private Order order;
    
    @TestVisible
    private List<Order_Product__c> orderProducts = new List<Order_Product__c>();

    public ExternalDataQueueable(External_Data_Load__c loadRecord) {
        this.loadRecord = loadRecord;
    }

    public void execute(QueueableContext context) {
        loadRecord.Status__c = MessageUtility.STATUS_SUCCESS;
        loadRecord.Error_Message__c = '';

        try {
            processPayload(loadRecord);
        } catch (Exception ex) {
            loadRecord.Status__c = MessageUtility.STATUS_FAILED;
            loadRecord.Error_Message__c += ex.getMessage();
        }

        EDLDataService.upsertEDL(loadRecord);
    }

    @TestVisible
    private void processPayload(External_Data_Load__c loadRecord) {
        if (Test.isRunningTest() && loadRecord.Payload__c == 'throw') {
            throw new DmlException(MessageUtility.ERROR_DML_PROBLEM);
        }

        ExternalDataWrapper dataWrapper = parsePayload(loadRecord);
        if (dataWrapper == null) {
            return;
        }

        if (!validateOrderExists(dataWrapper, loadRecord)) {
            return;
        }

        if (!upsertAccount(dataWrapper, loadRecord)) {
            return;
        }

        if (!upsertOrder(dataWrapper, loadRecord)) {
            return;
        }

        upsertOrderItems(dataWrapper, loadRecord);
    }

    private ExternalDataWrapper parsePayload(External_Data_Load__c loadRecord) {
        try {
            return (ExternalDataWrapper) JSON.deserialize(loadRecord.Payload__c, ExternalDataWrapper.class);
        } catch (Exception ex) {
            loadRecord.Status__c = MessageUtility.STATUS_FAILED;
            loadRecord.Error_Message__c = MessageUtility.ERROR_INVALID_JSON_PREFIX + ex.getMessage() + '\n';
            return null;
        }
    }

    private Boolean validateOrderExists(ExternalDataWrapper dataWrapper, External_Data_Load__c loadRecord) {
        if (dataWrapper.order == null) {
            loadRecord.Status__c = MessageUtility.STATUS_FAILED;
            loadRecord.Error_Message__c = MessageUtility.ERROR_MISSING_ORDER_INFO;
            return false;
        }
        return true;
    }

    private Boolean upsertAccount(ExternalDataWrapper dataWrapper, External_Data_Load__c loadRecord) {
        if (!Test.isRunningTest()) {
            custAccount = ExternalDataService.mapAccount(dataWrapper.order, loadRecord);
        }
        if (custAccount == null) {
            loadRecord.Status__c = MessageUtility.STATUS_FAILED;
            return false;
        }
        if (custAccount.Id == null) {
            AccountDataService.upsertAccount(custAccount);
        }
        return true;
    }

    private Boolean upsertOrder(ExternalDataWrapper dataWrapper, External_Data_Load__c loadRecord) {
        if (!Test.isRunningTest()) {
            order = ExternalDataService.mapOrder(dataWrapper.order, loadRecord, custAccount.Id);
        }
        if (order == null) {
            loadRecord.Status__c = MessageUtility.STATUS_FAILED;
            return false;
        }
        OrderDataService.upsertOrder(order);

        loadRecord.Order__c = order.Id;
        return true;
    }

    private void upsertOrderItems(ExternalDataWrapper dataWrapper, External_Data_Load__c loadRecord) {
        if (!Test.isRunningTest()) {
            orderProducts = ExternalDataService.mapOrderItems(dataWrapper.orderProducts, loadRecord, order.Id);
        }
        if (!orderProducts.isEmpty()) {
            List<Database.UpsertResult> upsertResults = OrderProductDataService.upsertOrderProducts(orderProducts);
            for (Database.UpsertResult res : upsertResults) {
                if (!res.isSuccess()) {
                    for (Database.Error err : res.getErrors()) {
                        loadRecord.Error_Message__c += MessageUtility.ERROR_ORDER_PRODUCT_UPSERT_PREFIX + err.getMessage() + '\n';
                        loadRecord.Status__c = MessageUtility.STATUS_PARTIAL_SUCCESS;
                    }
                }
            }
        } else {
            loadRecord.Status__c = MessageUtility.STATUS_PARTIAL_SUCCESS;
            loadRecord.Error_Message__c += MessageUtility.ERROR_NO_VALID_ORDER_ITEMS;
        }
    }
}