force-app/main/default/objects/Order_Product__c/Order_Product__c.object-meta.xml
<CustomObject>
    <label>Order Product</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Order Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderProductDataService.cls
public with sharing class OrderProductDataService {

    public static List<Database.UpsertResult> upsertOrderProducts(List<Order_Product__c> orderProducts) {
        if (orderProducts != null && !orderProducts.isEmpty()) {
            return Database.upsert(orderProducts, false);
        } else {
            return new List<Database.UpsertResult>();
        }
    }

    public static List<Order_Product__c> getOrderProductsByOrderAndProducts(Id orderId, Set<String> validProductIds) {
        if (orderId == null || validProductIds == null || validProductIds.isEmpty()) {
            return new List<Order_Product__c>();
        }

        return [
            SELECT Id, Product__r.Id
            FROM Order_Product__c
            WHERE Order__c = :orderId
            AND Product__c IN :validProductIds
            WITH SECURITY_ENFORCED
        ];
    }

}